package com.analysis;

public enum Algorithms{LINEAR_REGRESSION, POISSON_REGRESSION,LOGISTIC_REGRESSION,
	NEGATIVE_BINOMIAL_REGRESSION,MIXED_EFFECTS_MODEL,NEURAL_NETWORKS,RANDOM_FOREST,
	KNN,SVM,GAUSSIAN_PROCESS,NAIVE_BAYES};
