//created on: Mar 25, 2015
package analyst

//list any import classes here.



//declare any global variables here


rule "Always run linear regression"

    when
        //conditions
    then
        //actions

end

rule "If positive integers, run models good for positive integers (poisson regression)"

    when
        //conditions
    then
        //actions

end

rule "If random forest worked well, and other algos did not, then proceed to feature selection"

    when
        //conditions
    then
        //actions
end


rule "If there are many outliers use RANSAC"

	when

	then

end


